databases:
  - name: sgcc-db
    databaseName: sgcc
    user: admin_sgcc
    plan: free
    region: ohio

services:
  - type: web
    name: sgcc-app
    env: docker
    plan: free
    region: ohio
    healthCheckPath: /
    envVars:
      # Extrai as informações de conexão do banco de dados gerado no Render e as injeta como variáveis de ambiente para o Spring Boot
      - key: DB_HOST
        fromDatabase:
          name: sgcc-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sgcc-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: sgcc-db
          property: database

      # Monta a URL de conexão do banco de dados usando as variáveis extraídas
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sgcc-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sgcc-db
          property: password

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate